### ISSUE TITLE
Qt version

### ISSUE THREAD

**Issue by ghost** [user1095108/qtnanosvg#2]
Hi, what version qt and compiler do you use. I want to build a project but get a lot of errors
![image](https://user-images.githubusercontent.com/22058642/137300763-a7f74867-a51e-4809-9fb5-4ac24bacf294.png)

**Comment by user1095108** [comment]
Hello, I am using `gcc version 11.1.0` on arch linux. Everything works on arch. Make sure to have c++20 support, though the code could be ported to c++17, as it's not that sophisticated. Don't forget to `git submodule update --init`.

The code works both with latest qt5 and qt6 on my system.

Problems on windows are to be expected. If you take a look into the example.pro file, there's a g++-only section, but I think in this case there's a problem with your install. The code appears to have compiled, but the linker is having problems linking.

**Comment by ghost** [comment]
disabling 
```
#*-g++* {
#  QMAKE_CFLAGS = -pedantic -Wall -Wextra -fno-stack-protector -fno-plt

#  unix:QMAKE_CXXFLAGS_DEBUG *= -fsanitize=address,undefined
#  unix:QMAKE_LFLAGS_DEBUG *= -fsanitize=address,undefined

#  QMAKE_CFLAGS_RELEASE *= -Ofast -DNDEBUG
#  QMAKE_CXXFLAGS_RELEASE *= -Ofast -DNDEBUG -fno-stack-protector -fno-plt

#  QMAKE_LFLAGS *= -fno-stack-protector -fuse-ld=gold
#}
```

helps)))
5.15.2 MinGW 8.1 rung great
Binaries:
[Win X64.zip](https://github.com/user1095108/qtnanosvg/files/7345706/Win.X64.zip)

**Comment by user1095108** [comment]
Thank you, I have updated the `.pro` file, so maybe it will now work out of the box under windows. IMO, it was the address sanitizer that was causing problems.
